### ISSUE TITLE
Jersey serialization

### ISSUE THREAD

**Issue by jkerak** [SteKoe/amcharts-java#1]
I have an existing  Spring Boot API that utilizes Jersey2/JAX-RS for serialization.  How feasible is it for Jackson to do the serialization, as opposed to GSON.  Essentially what I'd like to do is the following:

`return Response.ok(amChart).build()`

Is this possible?

**Comment by SteKoe** [comment]
Hi @jkerak,

I have created an example project using Jersey for serialization. You can clone it from here: https://github.com/SteKoe/amcharts-java-examples-jersey
