### ISSUE TITLE
missing licence

### ISSUE THREAD

**Issue by rpionke** [SteKoe/amcharts-java#2]
Hi @SteKoe,

we want to use your amcharts java implementation in our company, but we can't cause you have not licensed your source code. Can u please tell us under which licence did u uploaded your implementation?
If you have trouble to choose the right Open Source licence, https://choosealicense.com/ and https://help.github.com/articles/licensing-a-repository/ are a good starting point.

Kind Regards,
Raphael

**Comment by SteKoe** [comment]
Hi Raphael,

thanks for your request. I have added a LICENSE.md (MIT) which applies to all revisions of this repository. Hence, feel free to use this repo and the source code in your company! :)

Best regards,
Stephan

**Comment by rpionke** [comment]
Thanks for your quick response!
