### ISSUE TITLE
AmCharts V4

### ISSUE THREAD

**Issue by envas** [SteKoe/amcharts-java#3]
Hi Stephan,

I started to analyze how to parse the V4 documentation and I see it's not easy to find a cssQuery to find the proper items. Any thoughts about AmCharts V4 Java API.  

BTW - is there any reason, except intellectual property protection, why you removed the helper classes from the repository. Especially the core of the extraction, AmChartsWebsiteExtractor. 

Robert

**Comment by SteKoe** [comment]
Hi Robert,

I am sorry to say that, but I have not planned to add V4 support to this repository. Anyhow: I have added the classes you mentioned, since it was not intended to remove them.

Regards
Stephan

**Comment by envas** [comment]
Hi Stephan,

thank you for adding missing classes.

In the meantime, I contacted amCharts support and asked for a little bit better-structured reference. They have a full reference available in JSON format. This huge document contains all JavaScript definitions, however, it should be easy to extract only classes and accessors (properties) for a Java API, anyway easier than traversing the DOM with jsoup.

I plan to generate the Java API for V4, it should be an open source project as well.

Regards
Robert

**Comment by SteKoe** [comment]
Hi Robert,

would you mind to share the JSON reference they provided you? And of course the repository where you are implementing the Java API v4?

Regards
Stephan

**Comment by envas** [comment]
Not sure if I am allowed to share the JSON file, I got it from AmChart support in a private discussion. I will ask them. 

And yes, when the API will be ready, I will share the API and the generator code, as you did for V3.

Robert
